apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi  # Size of the PV
  accessModes:
    - ReadWriteMany  # This allows multiple Pods to mount the PV
  nfs:
    path: /path/to/nfs # The path on the NFS server
    server: x.x.x.x  # The NFS server's IP or hostname
  persistentVolumeReclaimPolicy: Retain
