apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany  # Must match the access mode of the PV
  resources:
    requests:
      storage: 1Gi  # Size of the requested storage
  volumeName: nfs-pv  # The name of the PV to bind to
